EfCurso/Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EfCurso.Models
{
    public class Categoria
    {
        public int Id { get; set; }
        public string Nome { get; set; }

        public override string ToString()
        {
            return Id.ToString() + " " + Nome.ToString();
        }
    }
}

EfCurso/Models/ErrorViewModel.cs
using System;

namespace EfCurso.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EfCurso/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EfCurso.Models
{
    public class Funcionario
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public float Salario { get; set; }
        public string Cpf { get; set; }

    }
}

EfCurso/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EfCurso.Models
{
    public class Produto
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public Categoria Categoria { get; set; }

        public override string ToString()
        {
            return "id:" + this.Id + " Nome:" + this.Nome + " Categoria [" + this.Categoria.ToString() + "]";
        }
    }
}

EfCurso/Controllers/FuncionariosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Threading.Tasks;
using EfCurso.Models;
using EfCurso.Database;

namespace EfCurso.Controllers
{
    public class FuncionariosController : Controller
    {
        private readonly ApplicationDBContext database;

        public FuncionariosController(ApplicationDBContext database)
        {
            this.database = database;
        }

        public IActionResult Index()
        {
            var funcionarios = database.Funcionarios.ToList();
            return View(funcionarios);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            Funcionario funcionario = database.Funcionarios.First(f => f.Id == id);
            return View("Cadastrar", funcionario);
        }
        
        public IActionResult Deletar(int id)
        {
            Funcionario funcionario = database.Funcionarios.First(f => f.Id == id);
            database.Funcionarios.Remove(funcionario);
            database.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Salvar(Funcionario funcionario)
        {
            if(funcionario.Id == 0)
            {
                database.Funcionarios.Add(funcionario);
            }
            else
            {
                Funcionario funcionarioDoBanco = database.Funcionarios.First(f => f.Id == funcionario.Id);
                //Atualiza automaticamente o registro do banco, não precisa utilizar o metodo Update().
                funcionarioDoBanco.Nome = funcionario.Nome;
                funcionarioDoBanco.Cpf = funcionario.Cpf;
                funcionarioDoBanco.Salario = funcionario.Salario;
            }
            database.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

EfCurso/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EfCurso.Models;
using EfCurso.Database;
using Microsoft.EntityFrameworkCore;

namespace EfCurso.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDBContext database;

        public HomeController(ApplicationDBContext database)
        {
            this.database = database;
        }


        //private readonly ILogger<HomeController> _logger;

        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}

        public IActionResult Teste()
        {
            var listaCategorias = database.Categorias.ToList();

            listaCategorias.ForEach(categoria =>
            {

                Console.WriteLine("");

                Console.WriteLine(categoria.ToString());
            });

            return Content("teste");
        }

        public IActionResult CadastrarCategoria()
        {
            Categoria cat = new Categoria();
            cat.Nome = "Açougue";

            Categoria cat2 = new Categoria();
            cat2.Nome = "Mercearia";

            Categoria cat3 = new Categoria();
            cat3.Nome = "Padaria";

            database.Categorias.Add(cat);
            database.Categorias.Add(cat2);
            database.Categorias.Add(cat3);

            database.SaveChanges();

            return Content("Categorias");
        }

        public IActionResult Relacionamento()
        {
            //Produto p = new Produto();
            //p.Nome = "Doritos";
            //p.Categoria = database.Categorias.First(c => c.Id == 1);

            //Produto p1 = new Produto();
            //p1.Nome = "Frango";
            //p1.Categoria = database.Categorias.First(c => c.Id == 1);

            //Produto p2 = new Produto();
            //p2.Nome = "Bolo";
            //p2.Categoria = database.Categorias.First(c => c.Id == 2);

            //database.Add(p);
            //database.Add(p1);
            //database.Add(p2);

            //database.SaveChanges();

            //var listaDeProdutos = database.Produtos.Include(p => p.Categoria).ToList();

            //listaDeProdutos.ForEach(p =>
            //{
            //    Console.WriteLine(p.ToString());
            //});

            //Não utilizar Lazy Loading, deixa muito lento

            var listaDeProdutosDeUmaCategoria = database.Produtos.Include(p => p.Categoria).Where(p => p.Categoria.Id == 1).ToList();

            listaDeProdutosDeUmaCategoria.ForEach(p =>
            {
                Console.WriteLine(p.ToString());
            });

            return Content("Relacionamento");
        }
    }
}

EfCurso/Views/Funcionarios/Cadastrar.cshtml
@model EfCurso.Models.Funcionario

<h2>Cadastro de Funcionários</h2>

<form asp-controller="Funcionarios" asp-action="Salvar" method="post">
    <input type="hidden" asp-for="Id"/>
    <input class="form-control" type="text" asp-for="Nome" placeholder="Nome" />
    <input class="form-control" type="number" asp-for="Salario" placeholder="Salário" />
    <input class="form-control" type="text" asp-for="Cpf" placeholder="CPF" />
    <button class="btn btn-success">Cadastrar</button>
</form>

EfCurso/Views/Funcionarios/Index.cshtml
@model IEnumerable<EfCurso.Models.Funcionario>


<h2>Lista de Funcionários</h2>

<a href="/Funcionarios/Cadastrar" class="btn btn-success">Novo Funcionário</a>
<hr />
@foreach (var funcionario in Model)
{
    <p>Nome : @funcionario.Nome</p>
    <p>CPF: @funcionario.Cpf</p>
    <p>Salário: @funcionario.Salario</p>
    <a href="/Funcionarios/Editar/@funcionario.Id" class="btn btn-primary">Editar</a>
    <a href="/Funcionarios/Deletar/@funcionario.Id" class="btn btn-danger">Deletar</a>
    <hr />
}

EfCurso/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EfCurso/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EfCurso</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EfCurso</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionarios" asp-action="Index">Funcionários</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EfCurso - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>